### PR TITLE
Added User Management, Password/SSO Auth Methods, and Audit

### PR DESCRIPTION
**Pull request by gaokevin1**
## Related Issues

Fixes https://github.com/descope/etc/issues/6242

## Related PRs

| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |

## Description

Adding User Management, Auth Methods, and Audit Functions to the PHP SDK.

## Must

- [ ] Tests
- [ ] Documentation (if applicable)

### CODE REVIEW

**Review by gshriki — DISMISSED** [review]
Looking good.
Need to add multi-region support

**Comment by chris4490** [comment]
Looks good to me as well. Ship it if you want.

**Review by chris4490 — APPROVED** [review]

**Comment by chris4490** [comment]
@gaokevin1 we good to merge?

**Comment by chris4490** [comment]
@gaokevin1 we good to merge or still working on envs?

**Comment by gaokevin1** [comment]
There's a test that's failing, I need to fix then we'll merge. Will be done today was working on other shit yesterday.

**Comment by chris4490** [comment]
All good, just had a demo call that they asked about PHP, so it'll be nice to have this stuff in there for them when they start poking at it.

**Review by chris4490 — APPROVED** [review]

**Pull request merged**
